name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: [Debug, Release]
    steps:
      - uses: actions/checkout@v1
      - name: Checkout submodules
        run: |
          git submodule init
          git submodule update
      - name: Setup MSBuild.exe
        uses: warrenbuckley/Setup-MSBuild@v1
      - name: Build
        run: |
          mkdir artifacts
          cd src
          msbuild foo_listenbrainz2.sln -m -p:Configuration=${Env:CONFIGURATION}
          cp ${Env:CONFIGURATION}\foo_listenbrainz2\foo_listenbrainz2.dll ..\artifacts
        env:
          CONFIGURATION: ${{ matrix.configuration }}
      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: foo_listenbrainz2-${{ matrix.configuration }}
          path: artifacts/

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: foo_listenbrainz2-Release
          path: artifacts/
      - name: Generate checksums
        run: |
          cd artifacts
          sha256sum * > SHA256SUMS
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}